Repository graphp/algorithms, pull requests merged in 2018-10, with the labels that each got.

#27 Add max depth parameter to breadth first search
  src/Search/BreadthFirst.php
  tests/Search/BreadthFirstTest.php
Labels: new feature

#25 Replace recursive topological sort with iterative algorithm
  src/TopologicalSort.php
Labels: BC break, new feature

#35 Clean up dead code for depth first search
  src/Search/DepthFirst.php
Labels: easy pick, maintenance
